apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  version: 1.3.2
  executor: CeleryExecutor
  loadExamples: true
  exposeConfig: true
  webservers:
    roleGroups:
      default:
        config:
          credentialsSecret: simple-airflow-credentials
  workers:
    roleGroups:
      default:
        config:
          credentialsSecret: simple-airflow-credentials
  schedulers:
    roleGroups:
      default:
        config:
          credentialsSecret: simple-airflow-credentials