apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  version: 1.3.2
  nodes:
    roleGroups:
      default:
        config:
          credentialsSecret: simple-airflow-credentials
