apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  version: 2.2.3-python3.8
  executor: CeleryExecutor
  loadExamples: true
  exposeConfig: true
  webservers:
    roleGroups:
      default:
        config:
          credentialsSecret: simple-airflow-credentials
  workers:
    roleGroups:
      default:
        config:
          credentialsSecret: simple-airflow-credentials
        replicas: 2
  schedulers:
    roleGroups:
      default:
        config:
          credentialsSecret: simple-airflow-credentials